Server:
  Host: localhost
  Port: 8080

MySQL:
  Host: localhost
  Port: 3306
  Username: root
  Password: root
  Database: test

OpenAI:
  BaseUrl: https://api.openai.com
  Model: gpt-3.5-turbo
  ApiKey: sk-1234567890
